=== TejeshwiniRS/XML_STATIC_WEBPAGE/hospital_dtd.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT hospitalinfo (services,contact+)>
<!ATTLIST hospitalinfo
  xmlns CDATA #FIXED ''>

<!ELEMENT services (speciality,list+)>
<!ATTLIST services
  xmlns CDATA #FIXED ''>

<!ELEMENT contact (info)>
<!ATTLIST contact
  xmlns CDATA #FIXED ''>

<!ELEMENT speciality (#PCDATA)>
<!ATTLIST speciality
  xmlns CDATA #FIXED ''>

<!ELEMENT list (ul)>
<!ATTLIST list
  xmlns CDATA #FIXED ''>

<!ELEMENT info (#PCDATA)>
<!ATTLIST info
  xmlns CDATA #FIXED ''>

<!ELEMENT ul (#PCDATA)>
<!ATTLIST ul
  xmlns CDATA #FIXED ''>

=== TejeshwiniRS/XML_STATIC_WEBPAGE/hospital_info.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hospitalinfo SYSTEM "hospital_dtd.dtd"> <!--LINKING DTD WITH XML DOC-->

<hospitalinfo>  <!--root element-->
<services>    <!--child element-->
<speciality>SPECIALITIES</speciality>   <!--subchild element-->
<list>
<ul>Ortho</ul></list>
<list><ul>Cardio</ul></list>
<list><ul>Optho</ul></list>
<list><ul>Nephro</ul></list>
<list><ul>Neuro</ul></list>
<list><ul>onco</ul></list>
</services>
<contact>  <!--sibling of child element-->
<info>ADDRESS   : Rajaji nagar,Bangalore</info>
</contact>
<contact>  <!--sibling of child element-->
<info>PHONE NO :9876543210</info>
</contact>
<contact>  <!--sibling of child element-->
<info>EMAIL ID :xyzhospital@yahoo.com</info>
</contact>
</hospitalinfo>
